name: Deliver to beta

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  unit-test:
    name: Runs unit test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          # Create a properties file using echo command
          echo 'API_URL="${{secrets.API_URL}}"' > ${{github.workspace}}/secrets.defaults.properties
          echo "ALIAS=${{secrets.ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_PASS=${{secrets.KEY_PASS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_ALIAS=${{secrets.KEY_ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
      - run: fastlane unit_test_verification

  distribute:
    needs: unit-test
    name: Deliver Firebase App Distribution
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          # Get release version
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          # Create a properties file and keystore using echo command
          echo "${{secrets.KEYSTORE}}" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > ${{github.workspace}}/app/keystore.jks
          echo 'API_URL="${{secrets.API_URL}}"' > ${{github.workspace}}/secrets.defaults.properties
          echo "ALIAS=${{secrets.ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_PASS=${{secrets.KEY_PASS}}" >> ${{github.workspace}}/secrets.defaults.properties
          echo "KEY_ALIAS=${{secrets.KEY_ALIAS}}" >> ${{github.workspace}}/secrets.defaults.properties
      - run: fastlane increment_version id:${{APP_ID}} token:${{FIREBASE_CI_TOKEN}}
      - run: fastlane set_version_name version:${{ env.RELEASE_VERSION }}
      - run: fastlane generate_apk
      - run: fastlane distribute id:${{APP_ID}} testers:${{vars.TESTERS}} notes:${{vars.NOTES}} token:${{FIREBASE_CI_TOKEN}}


